# Generated by Django 4.2.6 on 2024-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('DeviceTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
