# Generated by Django 4.2.6 on 2024-04-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cpu_gpu_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('EquipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=100)),
                ('DeviceSerial', models.CharField(max_length=50)),
                ('IsOnsiteOnly', models.BooleanField(default=False)),
                ('CPUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cpu')),
                ('DeviceTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.devicetype')),
                ('GPUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gpu')),
                ('RAMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ram')),
            ],
        ),
    ]
