# Generated by Django 4.2.6 on 2024-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
