# Generated by Django 4.2.6 on 2024-04-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_booking_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Availability',
            field=models.BooleanField(default=True),
        ),
    ]
