# Generated by Django 4.2.6 on 2024-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_equipment_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
